version: "3"
services:
  reverseproxy:
    image: recipes-social-network-api-gateway:v1.01
    container_name: recipes-api-gateway
    environment:
      APP_URL: $APP_URL
      PORT: $PORT
      AMQP_URL: $AMQP_URL
      URI_MONGODB: $URI_MONGODB
      EXPIRES_IN: $EXPIRES_IN
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      JWT_SECRET: $JWT_SECRET
    ports:
      - 80:3000
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - recipes_network

  recipe-microservice:
    image: recipes-social-network-recipe-microservice:v1.01
    container_name: recipe-microservice
    environment:
      APP_URL: $APP_URL
      PORT: $PORT
      AMQP_URL: $AMQP_URL
      URI_MONGODB: $URI_MONGODB
      EXPIRES_IN: $EXPIRES_IN
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      JWT_SECRET: $JWT_SECRET
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - recipes_network

  comment-microservice:
    image: recipes-social-network-comment-microservice:v1.01
    container_name: comment-microservice
    environment:
      APP_URL: $APP_URL
      PORT: $PORT
      AMQP_URL: $AMQP_URL
      URI_MONGODB: $URI_MONGODB
      EXPIRES_IN: $EXPIRES_IN
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      JWT_SECRET: $JWT_SECRET
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - recipes_network

  user-microservice:
    image: recipes-social-network-user-microservice:v1.01
    container_name: user-microservice
    environment:
      APP_URL: $APP_URL
      PORT: $PORT
      AMQP_URL: $AMQP_URL
      URI_MONGODB: $URI_MONGODB
      EXPIRES_IN: $EXPIRES_IN
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      JWT_SECRET: $JWT_SECRET
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - recipes_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - recipes_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - 27017
    networks:
      - recipes_network

volumes:
  mongodb:

networks:
  recipes_network:
