version: "3"
services:
  reverseproxy:
    image: igomezdockerhub/recipes-social-network-api-gateway:v1.01
    container_name: recipes-api-gateway
    environment:
      APP_URL: https://recipes-social-network.com
      PORT: 3000
      AMQP_URL: amqp://recipes-rabbitmq:5672
      URI_MONGODB: mongodb://recipes-mongodb:27017/recipes-social-network
      JWT_SECRET: JWTrBOf5a7mX#vN
      EXPIRES_IN: 12h
    ports:
      - 80:3000
    depends_on:
      - recipes-mongodb
      - recipes-rabbitmq
    restart: always
    networks:
      - recipes_network

  recipe-microservice:
    image: recipes-social-network-recipe-microservice:v1.01
    container_name: recipe-microservice
    environment:
      APP_URL: https://recipes-social-network.com
      PORT: 3000
      AMQP_URL: amqps://adxxikja:9-K67aUWBm0_l4h9gNcw9YYmWOW-gu8u@shrimp.rmq.cloudamqp.com/adxxikja
      URI_MONGODB: mongodb://localhost:27017/recipes-social-network
    depends_on:
      - recipes-mongodb
      - recipes-rabbitmq
    restart: always
    networks:
      - recipes_network

  comment-microservice:
    image: recipes-social-network-comment-microservice:v1.01
    container_name: comment-microservice
    environment:
      APP_URL: https://recipes-social-network.com
      PORT: 3000
      AMQP_URL: amqps://adxxikja:9-K67aUWBm0_l4h9gNcw9YYmWOW-gu8u@shrimp.rmq.cloudamqp.com/adxxikja
      URI_MONGODB: mongodb://localhost:27017/recipes-social-network
    depends_on:
      - recipes-mongodb
      - recipes-rabbitmq
    restart: always
    networks:
      - recipes_network

  user-microservice:
    image: recipes-social-network-user-microservice:v1.01
    container_name: user-microservice
    environment:
      APP_URL: https://recipes-social-network.com
      PORT: 3000
      AMQP_URL: amqps://adxxikja:9-K67aUWBm0_l4h9gNcw9YYmWOW-gu8u@shrimp.rmq.cloudamqp.com/adxxikja
      URI_MONGODB: mongodb://localhost:27017/recipes-social-network
    depends_on:
      - recipes-mongodb
      - recipes-rabbitmq
    restart: always
    networks:
      - recipes_network

  recipes-rabbitmq:
    image: rabbitmq:3-management
    container_name: recipes-rabbitmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - recipes_network

  recipes-mongodb:
    image: mongo:latest
    container_name: recipes-mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - 27017
    networks:
      - recipes_network

volumes:
  mongodb:

networks:
  recipes_network:
