version: "3"
services:
  reverseproxy:
    image: recipes-social-network-api-gateway:v1.01
    container_name: recipes-api-gateway
    environment:
      APP_URL: https://recipes-social-network.com
      PORT: 3000
      AMQP_URL: amqp://rabbitmq:5672
      URI_MONGODB: mongodb://mongodb:27017/recipes-social-network
      JWT_SECRET: JWTrBOf5a7mX#vN
      EXPIRES_IN: 12h
    ports:
      - 80:3000
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - recipes_network

  recipe-microservice:
    image: recipes-social-network-recipe-microservice:v1.01
    container_name: recipe-microservice
    environment:
      APP_URL: https://recipes-social-network.com
      PORT: 3000
      AMQP_URL: amqp://rabbitmq:5672
      URI_MONGODB: mongodb://mongodb:27017/recipes-social-network
      JWT_SECRET: JWTrBOf5a7mX#vN
      EXPIRES_IN: 12h
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - recipes_network

  comment-microservice:
    image: recipes-social-network-comment-microservice:v1.01
    container_name: comment-microservice
    environment:
      APP_URL: https://recipes-social-network.com
      PORT: 3000
      AMQP_URL: amqp://rabbitmq:5672
      URI_MONGODB: mongodb://mongodb:27017/recipes-social-network
      JWT_SECRET: JWTrBOf5a7mX#vN
      EXPIRES_IN: 12h
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - recipes_network

  user-microservice:
    image: recipes-social-network-user-microservice:v1.01
    container_name: user-microservice
    environment:
      APP_URL: https://recipes-social-network.com
      PORT: 3000
      AMQP_URL: amqp://rabbitmq:5672
      URI_MONGODB: mongodb://mongodb:27017/recipes-social-network
      JWT_SECRET: JWTrBOf5a7mX#vN
      EXPIRES_IN: 12h
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - recipes_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - recipes_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - 27017
    networks:
      - recipes_network

volumes:
  mongodb:

networks:
  recipes_network:
