apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: igomezdockerhub/recipes-social-network-api-gateway:v1.03
        name: api-gateway
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: APP_URL
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: PORT
        - name: AMQP_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AMQP_URL
        - name: URI_MONGODB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URI_MONGODB
        - name: EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: EXPIRES_IN
      restartPolicy: Always