apiVersion: v1
kind: Service
metadata:
  labels:
    app: comment-microservice
  name: comment-microservice
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app: comment-microservice