apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        api: external
    spec:
      containers:
      - name: frontend
        image: igomezdockerhub/recipes-social-network-frontend:v1.02
        imagePullPolicy: Always
        ports:
          - containerPort: 80